server:
  port: 8000

spring:
  application:
    name: gateway

  profiles:
    active: dev

  config:
    import: configserver:http://${CONFIG_SERVER_ADDRESS}

  cloud:
    config:
      fail-fast: true